# Generated by Django 4.1.7 on 2023-03-16 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_wishcategory_alter_wishitem_item_wishitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishitem',
            name='category',
        ),
        migrations.AddField(
            model_name='wishitem',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='WishCategory',
        ),
    ]
