# Generated by Django 4.1.7 on 2023-03-17 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_wishitem_category_wishitem_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishitem',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to='main.item'),
        ),
    ]
