# Generated by Django 4.1.7 on 2023-03-17 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_wishitem_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishitem',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
